# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

trigger:
- main
- feature/*

pool:
  vmImage: ubuntu-latest

steps:
- script: echo Hello, world!
  displayName: 'Run a one-line script'

- script: |
    echo Add other tasks to build, test, and deploy your project.
    echo See https://aka.ms/yaml
  displayName: 'Run a multi-line script'

- script: |
    # Get the hoverfly stub engine
    wget https://github.com/SpectoLabs/hoverfly/releases/download/v1.3.2/hoverfly_bundle_linux_amd64.zip -O hoverfly.zip
    unzip hoverfly.zip

    # Start hoverfly running in simulate mode, and read in an empty stub config
    ./hoverctl start
    ./hoverctl mode simulate
    ./hoverctl import tests/integration/stubs/empty.stub.json

    # Now hit a non-existent API in the stub
    curl -H "Content-Type application/json" -X POST -d '{"mode":"simulate"}' http://localhost:8888/api/state

    # Now start the app running, and capture the PID so we can kill it later
    # Note that we're setting HTTP_PROXY to point to the Hoverfly stub, so that all tests go via Hoverfly
    #HTTP_PROXY=http://localhost:8500 node helloworld.js &
    #APP_PID=$!



    # Stop Hoverfly
    ./hoverctl stop
  displayName: 'Run tests against an empty stub'